### ISSUE TITLE
[Question] Not using Gitflow during the development process

### ISSUE THREAD

**Issue by suho** [SchwartzLizer/NimbleSurvey#5]
## Issue

Regarding [technical requirement](https://docs.google.com/document/d/1CpbVBdyFmKKYO2BhAxam0_Cz9ByMKsnXNX-Jmeb3M80/edit#heading=h.fn5jf7chmf6d), you should use Git (make regular commits and merge code using pull requests) during the development process. However, I do not see any pull requests in this repository. Could you clarify why you did not use pull requests?

**Comment by SchwartzLizer** [comment]
@suho I apologize for any confusion. I believe I simply enabled the branch protection rule, and everything is set. That is incorrect. When I need to merge into the main branch, I need to file a pull request on GitHub. It will not happen again.

![Web capture_31-10-2023_1819_github.com] (https://github.com/SchwartzLizer/NimbleSurvey/assets/54163797/47da7efd-8985-46ff-9965-b65dc7ac14e2)
