### ISSUE TITLE
[Bug] Some Unit and UI Tests have failed

### ISSUE THREAD

**Issue by suho** [SchwartzLizer/NimbleSurvey#7]
## Issue

Currently, some Unit and UI tests have failed.

![image](https://github.com/SchwartzLizer/NimbleSurvey/assets/19943832/2dda9ca3-07bb-4ca9-ad3f-d811786617fe)

## Expected

It's expected that all tests should be passed.

## Steps to reproduce

1. Open the project with Xcode.
2. Run all tests.

**Comment by SchwartzLizer** [comment]
Refactor all unit tests done
